/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { core } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    date<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "DateTime";
    json<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "JSON";
    timestamp<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "Timestamp";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    date<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "DateTime";
    json<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "JSON";
    timestamp<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "Timestamp";
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  PostJobInput: { // input type
    description: string; // String!
    price: number; // Int!
    title: string; // String!
  }
  UserEditInput: { // input type
    email: string; // String!
    name: string; // String!
    password: string; // String!
  }
  UserLoginInput: { // input type
    email: string; // String!
    password: string; // String!
  }
  UserRegisterInput: { // input type
    email: string; // String!
    name: string; // String!
    password: string; // String!
  }
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  DateTime: any
  JSON: any
  Timestamp: any
}

export interface NexusGenObjects {
  Job: { // root type
    createdAt: NexusGenScalars['Timestamp']; // Timestamp!
    description: string; // String!
    id: string; // ID!
    price: number; // Int!
    title: string; // String!
    updatedAt: NexusGenScalars['Timestamp']; // Timestamp!
    userId: string; // String!
  }
  Mutation: {};
  Query: {};
  User: { // root type
    createdAt: NexusGenScalars['Timestamp']; // Timestamp!
    email: string; // String!
    id: string; // ID!
    name: string; // String!
    password: string; // String!
    updatedAt: NexusGenScalars['Timestamp']; // Timestamp!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  Job: { // field return type
    createdAt: NexusGenScalars['Timestamp']; // Timestamp!
    description: string; // String!
    id: string; // ID!
    price: number; // Int!
    title: string; // String!
    updatedAt: NexusGenScalars['Timestamp']; // Timestamp!
    userId: string; // String!
  }
  Mutation: { // field return type
    edit: NexusGenRootTypes['User'] | null; // User
    login: NexusGenRootTypes['User'] | null; // User
    logout: NexusGenRootTypes['User'] | null; // User
    postJob: NexusGenRootTypes['Job'] | null; // Job
    register: NexusGenRootTypes['User'] | null; // User
  }
  Query: { // field return type
    getJobs: Array<NexusGenRootTypes['Job'] | null> | null; // [Job]
    getUsers: Array<NexusGenRootTypes['User'] | null> | null; // [User]
  }
  User: { // field return type
    createdAt: NexusGenScalars['Timestamp']; // Timestamp!
    email: string; // String!
    id: string; // ID!
    name: string; // String!
    password: string; // String!
    updatedAt: NexusGenScalars['Timestamp']; // Timestamp!
  }
}

export interface NexusGenFieldTypeNames {
  Job: { // field return type name
    createdAt: 'Timestamp'
    description: 'String'
    id: 'ID'
    price: 'Int'
    title: 'String'
    updatedAt: 'Timestamp'
    userId: 'String'
  }
  Mutation: { // field return type name
    edit: 'User'
    login: 'User'
    logout: 'User'
    postJob: 'Job'
    register: 'User'
  }
  Query: { // field return type name
    getJobs: 'Job'
    getUsers: 'User'
  }
  User: { // field return type name
    createdAt: 'Timestamp'
    email: 'String'
    id: 'ID'
    name: 'String'
    password: 'String'
    updatedAt: 'Timestamp'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    edit: { // args
      user: NexusGenInputs['UserEditInput']; // UserEditInput!
    }
    login: { // args
      user: NexusGenInputs['UserLoginInput']; // UserLoginInput!
    }
    postJob: { // args
      job: NexusGenInputs['PostJobInput']; // PostJobInput!
    }
    register: { // args
      user: NexusGenInputs['UserRegisterInput']; // UserRegisterInput!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: any;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}