# Generated by Django 4.1.7 on 2023-03-26 15:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OddJobsCo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='l_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='u_id',
            new_name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.CreateModel(
            name='Filters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OddJobsCo.listing')),
            ],
        ),
    ]
