# Generated by Django 4.1.7 on 2023-03-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OddJobsCo', '0002_rename_l_id_listing_id_rename_u_id_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
