# Generated by Django 4.1.7 on 2023-03-31 01:21

import OddJobsCo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OddJobsCo', '0005_user_groups_user_is_superuser_user_last_login_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', OddJobsCo.models.UserManager()),
            ],
        ),
    ]
