# Generated by Django 4.1.7 on 2023-05-05 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OddJobsCo', '0006_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('filter_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ListingFilter',
            fields=[
                ('listing_filter_id', models.AutoField(primary_key=True, serialize=False)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OddJobsCo.filter')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('option_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OddJobsCo.filter')),
            ],
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='id',
            new_name='listing_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='price',
        ),
        migrations.DeleteModel(
            name='Filters',
        ),
        migrations.AddField(
            model_name='listingfilter',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OddJobsCo.listing'),
        ),
    ]
