# Generated by Django 4.1.7 on 2023-05-05 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OddJobsCo', '0007_filter_listingfilter_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='filter',
        ),
        migrations.CreateModel(
            name='FilterOption',
            fields=[
                ('filter_option_id', models.AutoField(primary_key=True, serialize=False)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OddJobsCo.listing')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OddJobsCo.option')),
            ],
        ),
    ]
